### ISSUE TITLE
Topic Idea - Beginning React

### ISSUE THREAD

**Issue by aspencer8111** [Bloc/group-sessions#21]
Beginning React

Outline:

1. What is React?
2. What it is not.
3. Why use React over vanilla JS or jQuery?
4. `create-react-app`
5. State and Props
6. Building a simple todo app using React _(great way to compare if the student has already attended DOM manipulation session)_

**Comment by courtlandalves** [comment]
Two students that again have asked for this.

**Comment by courtlandalves** [comment]
Ping again! two more students!! Pretty pretty please quickly

**Comment by shannonio** [comment]
Completed
